version: "3.8"
services:
  mongodb:
    image: mongo
    container_name: mongodb
    environment:
    - PUID=1000
    - PGID=1000
    volumes:
    - ./mongodb/database:/data/db
    ports:
    - 8000:27017
    restart: unless-stopped
  starlette:
    build: ./app
    container_name: starlette
    volumes:
      - ./app:/opt/app
    ports:
      - 5000:5000
    depends_on: 
      - mongodb